---

  - name: Create {{ service }} user
    user: name={{ service }} comment={{ service }} shell=/bin/nologin createhome=no system=yes
    become: yes

  - name: Download HBase archive locally
    get_url:
      url: "{{ hbase_archive_url }}"
      dest: "/tmp/hbase.tar.gz"
      mode: 0600
      checksum: sha256:{{ hbase_archive_file_checksum256 }}
    run_once: true
    delegate_to: localhost

  - name: Copy and extract archive
    ansible.builtin.unarchive:
      src: "/tmp/hbase.tar.gz"
      dest: "/tmp"

  - name: Recursively remove directory
    ansible.builtin.file:
      path: "{{ hbase_path }}/{{ hbase_dir }}"
      state: absent
    become: yes

  - name: Rename dir
    command: mv -f {{ hbase_path }}/hbase-{{ hbase_version }} {{ hbase_path }}/{{ hbase_dir }}

  - name: Write config template
    ansible.builtin.command:
      cmd: "roles/hbase/files/hbase-config.sh"
    delegate_to: localhost

  - name: Write config template
    ansible.builtin.command:
      cmd: "roles/hbase/files/hbase-service-config.sh"
    delegate_to: localhost

  - name: Create hbase-site.xml
    template: src={{ hbase_config_path }}/hbase-site.xml.j2 dest={{ hbase_config_path }}/hbase-site.xml mode=0640


  - name: Create systemd unit env file
    template: src={{ hbase_config_path}}/systemd-env-{{ service }}.j2 dest=/etc/systemd-env-{{ service }} mode=0640
    become: yes

  - name: Create systemd unit for HBase master
    template: src={{ hbase_config_path}}/hbase-master.service.j2 dest=/etc/systemd/system/hbase-master.service mode=0600
    become: yes
    when: ansible_distribution != "FreeBSD"
    become: yes

  - name: Create systemd unit for HBase regionserver
    template: src={{ hbase_config_path}}/hbase-master.service.j2 dest=/etc/systemd/system/hbase-master.service mode=0600
    become: yes
    when: ansible_distribution != "FreeBSD"
    become: yes

  - name: Change ownership of {{ service }} dir
    ansible.builtin.file:
      path: "{{ hbase_path }}/{{ hbase_dir }}"
      state: directory
      recurse: yes
      owner: "{{ service }}"
      group: "{{ service }}"
    become: yes

  - name: Create {{ service }} log directory
    file:
      path: "{{ service_log_dir }}"
      state: directory
      mode: '0750'
      owner: "{{ service_user }}"
      group: "{{ service_user }}"
    become: yes
